version: "3.3"
services:

  db:
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_USER: trava
      POSTGRES_PASSWORD: trava
      POSTGRES_DB: trava
    ports:
      - "127.0.0.1:5432:5432"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 127.0.0.1:15672:15672

  # frontend ...

  api:
    build: api/
    ports:
      - "8081:8080"
    environment:
      api_base_url: "https://google.com/"
      db_host: "db"
    depends_on:
      - db
      - rabbitmq
    restart: unless-stopped

  rabbitworker:
    build: rabbitworker/
    environment:
      rabbit_host: "rabbitmq"
    depends_on:
      - rabbitmq
    restart: unless-stopped
