version: "3.3"
services:
  api:
    build: api/
    ports:
      - "8081:8080"
    environment:
      api_base_url: "https://google.com/"
      db_host: "db"
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_USER: trava
      POSTGRES_PASSWORD: trava
      POSTGRES_DB: trava
    ports:
      - "127.0.0.1:5432:5432"
