version: "3.3"
services:
  api:
    build: api/
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_USER: trava
      POSTGRES_PASSWORD: trava
      POSTGRES_DB: trava
    ports:
      - "127.0.0.1:5432:5432"
